### ISSUE TITLE
No results?

### ISSUE THREAD

**Issue by ldti** [twei55/covid19-grafana-datasource#1]
Hey. I am able to select the metric (country), but i am not able to get any results from any of them.
It also looks like i am getting a 502 error from the endpoint...

**Comment by twei55** [comment]
Can you give me some more context or the error message that is returned by the API? Which Grafana version are you using, how did you configure the datasource, which panel/visualization type are you using?

**Comment by ldti** [comment]
Hey.
Grafana is 6.6.2.
Source is JSON, as instructed in the website.
Trying to add as graph or anything else for that matter, getting this error in the web console:

`Failed to load resource: the server responded with a status of 500 (Internal Server Error)`
`:3000/api/datasources/proxy/5/query:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error) `

from the grafana log:
`t=2020-03-28T14:46:33+0300 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/5/query status=500 remote_addr=10.200.10.57 time_ms=230 size=290 referer="http://10.200.10.16:3000/d/RDANFJ9Wk/general?panelId=32&edit&fullscreen"`

**Comment by twei55** [comment]
I can see an error message "Internal server error" appearing in the upper left corner when I initialize a new panel. As soon as you select a metric in the query panel, this error should be gone. I tested this with Grafana 6.6.1 lately.

**Comment by twei55** [comment]
I can see requests from Grafana 6.6.2 in the logs and as far as I can see all respond with status 200.

**Comment by ldti** [comment]
Unfortunately the metric does not get saved, and no data gets shown..

Should I check with 6.6.1?



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by twei55** [comment]
Sorry, I tested this with 6.5.2 and the untagged docker version which is apparently 6.4.3. These versions work fine. There seems to be an issue with Grafana 6.6.x, need to investigate.

**Comment by ldti** [comment]
Thank you!



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by twei55** [comment]
Tested with 6.6.2, works for me. Are you sure that you selected the correct time range? Normally there is lack of one day, try to e.g. use last 7 or last 30 days.

**Comment by ldti** [comment]
I will try again in a few minutes.



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by ldti** [comment]
Yes, you were correct! Usually I don't select such long time ranges..

**Comment by ldti** [comment]
Might be worthwhile to add a paragraph about it on the site.

**Comment by twei55** [comment]
@ldti Thanks for your feedback. Yes, I will add a note. Hope that it works for you now. Stay healthy.

**Comment by ldti** [comment]
Thank you.



Sent from my Samsung Galaxy smartphone.



-------- Original message --------
